name: pkg-version-check

on:
  push:
    branches:
      - master

    paths-ignore:
      - 'released/**'

  pull_request:
    branches:
      - master

    paths-ignore:
      - 'released/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a version checker script
        run: bash ./version_check.sh
        env:
          MIST_USER: ${{ secrets.MIST_USER }}
          MIST_PASS: ${{ secrets.MIST_PASS }}
