name: yamllint
on:
  push:
    branches:
      - main
   
  pull_request:
    branches:
      - main
   
jobs:
  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        run: |
          make -j $(nproc) yamllint
